import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/utils/functions";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import WalletConnectProvider from "@/contexts/WalletConnectProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <WalletConnectProvider>
            <Navbar />
            {children}
          </WalletConnectProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
